language: java
install:
  - mkdir BuildTools
  - cd BuildTools
  - wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
  - java -jar BuildTools.jar >> /dev/null
  - cd ../PermissionsAPI
  - mvn install
